context:
  version: "14.0.3"

package:
  name: cypress
  version: ${{ version }}

source:
  url: https://registry.npmjs.org/cypress/-/cypress-${{ version }}.tgz
  sha256: fd1a0cd62a818bbd42fc17ae749ed9d7bdee6365e1dbb8e5c1bc395deeba4488

build:
  number: 0
  noarch: generic

requirements:
  build:
    - nodejs
    - pnpm
    - pnpm-licenses
  run:
    - nodejs

tests:
  - script:
      - cypress --help

about:
  license: MIT
  license_file:
    - LICENSE
    - third-party-licenses.txt
  summary: Fast, easy and reliable testing for anything that runs in a browser.
  homepage: https://github.com/cypress-io/cypress
  repository: https://github.com/cypress-io/cypress

extra:
  recipe-maintainers:
    - danielnachun
