context:
  version: "15.19.0"

package:
  name: cypress
  version: ${{ version }}

source:
  url: https://registry.npmjs.org/cypress/-/cypress-${{ version }}.tgz
  sha256: 046cb176f1007e71ce9f5a125df76353234b4dd6e9a3ef1ae50dc08898413d4d

build:
  number: 0
  noarch: generic

requirements:
  build:
    - nodejs
    - pnpm
    - pnpm-licenses
  run:
    - nodejs

tests:
  - script:
      - cypress --help

about:
  license: MIT
  license_file:
    - LICENSE
    - third-party-licenses.txt
  summary: Fast, easy and reliable testing for anything that runs in a browser.
  homepage: https://github.com/cypress-io/cypress
  repository: https://github.com/cypress-io/cypress

extra:
  recipe-maintainers:
    - danielnachun
