context:
  version: "15.20.0"

package:
  name: cypress
  version: ${{ version }}

source:
  url: https://registry.npmjs.org/cypress/-/cypress-${{ version }}.tgz
  sha256: 8f08f5b787b499dc63b17d5e04dc59043785e391d8fb7952fce58250265df52d

build:
  number: 0
  noarch: generic

requirements:
  build:
    - nodejs
    - pnpm
    - pnpm-licenses
  run:
    - nodejs

tests:
  - script:
      - cypress --help

about:
  license: MIT
  license_file:
    - LICENSE
    - third-party-licenses.txt
  summary: Fast, easy and reliable testing for anything that runs in a browser.
  homepage: https://github.com/cypress-io/cypress
  repository: https://github.com/cypress-io/cypress

extra:
  recipe-maintainers:
    - danielnachun
