context:
  version: "15.17.0"

package:
  name: cypress
  version: ${{ version }}

source:
  url: https://registry.npmjs.org/cypress/-/cypress-${{ version }}.tgz
  sha256: 37a0b99336f326ede58aa3905559969875d94c29ab469a9e3427398971fa2469

build:
  number: 0
  noarch: generic

requirements:
  build:
    - nodejs
    - pnpm
    - pnpm-licenses
  run:
    - nodejs

tests:
  - script:
      - cypress --help

about:
  license: MIT
  license_file:
    - LICENSE
    - third-party-licenses.txt
  summary: Fast, easy and reliable testing for anything that runs in a browser.
  homepage: https://github.com/cypress-io/cypress
  repository: https://github.com/cypress-io/cypress

extra:
  recipe-maintainers:
    - danielnachun
