context:
  version: "14.5.0"

package:
  name: cypress
  version: ${{ version }}

source:
  url: https://registry.npmjs.org/cypress/-/cypress-${{ version }}.tgz
  sha256: 87827b42d8fa90daa3c1fe2ff10373bc6baa4170c861779a43bd3fd1a59d22d2

build:
  number: 0
  noarch: generic

requirements:
  build:
    - nodejs
    - pnpm
    - pnpm-licenses
  run:
    - nodejs

tests:
  - script:
      - cypress --help

about:
  license: MIT
  license_file:
    - LICENSE
    - third-party-licenses.txt
  summary: Fast, easy and reliable testing for anything that runs in a browser.
  homepage: https://github.com/cypress-io/cypress
  repository: https://github.com/cypress-io/cypress

extra:
  recipe-maintainers:
    - danielnachun
